
author: Matt Greenfield
domain: mattgreenfield.co.uk
about: I'm Matt, a front end developer and web designer from Brighton, UK.I’m currently working for <a href="http://www.gene.co.uk/" target="_blank" class="text-emphasis">Gene</a>. I’m big on responsive and style guide based design. I also enjoy <a href="http://thebluesissue.co.uk/" target="_blank" class="text-emphasis">drumming</a>.</p>


collections:
  style-guide:
    output: false
  portfolio:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

# Serving
port: 1234

# markdown: kramdown

skills:
  - CSS
  - Sass
  - HTML5
  - Javascript
  - Git
  - jQuery
  - Accessibility
  - SVG
  - Jekyll
