
collections:
  portfolio:
    output: true
  style-guide:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
     layout: "default"
  -
    scope:
      path: ""
      type: "style-guide"
    values:
     layout: "default"



# Serving
port: 1234
