
author: Matt Greenfield
domain: mattgreenfield.co.uk

collections:
  style-guide:
    output: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

# Serving
port: 1234
